delivery_fee: "5,000 đ/km"
user_type:
  admin: 1
  shipper: 2
  chef: 3
  customer: 4

status:
  new_order: 1
  in_progress: 2
  done: 3

default_avatar: "https://dwrhx129r2-flywheel.netdna-ssl.com/wp-content/uploads/2015/08/blank-avatar.png"
